# Application ID should be unique for each input.topic/output.topic pair.
# It is what allows kafka streams to scale
application.id: zabbix-to-otlp
# Mandatory. Either sevone or zabbix (future netscout)
source: zabbix
bootstrap.servers: techarch-kafka2.srv.lab.bthpny.alticeusa.net:9092
input.topic: rednet.bluenet.com.optimum.monitoring.metrics.zabbix
output.topic: rednet.bluenet.com.optimum.monitoring.metrics.zabbix.streams.otlp
# Sample rate 1=100% allow us to filter out messages in case of extremely massive topics.
sample.rate: 1
# format: json / protobuf
format: json

